### ISSUE TITLE
Error in game server while requesting from browser...

### ISSUE THREAD

**Issue by Zalasanjay** [vampserv/node-poker-stack#11]
Getting this error message after requesting [localhost](http://localhost:3002/index.html)

my current versions are described bellow.

**System Win 7 (64bit) | Firefox Browser 74.0 (64-bit)**
`node-gyp@6.1.0
node@10.19.0
npm@6.13.4`

**game-server**
`"dependencies": {
    "crc": "0.2.0",
    "hoyle": "^0.2.2",
    "node-uuid": "^1.4.1",
    "pomelo": "2.2.7",
    "pomelo-logger": "^0.1.6",
    "redis": "^0.12.1"
  }`

**web-server**
`"dependencies": {
		"express": "3.4.0"
	}`

`[ERROR] console - Caught exception: TypeError: Cannot read property 'indexOf' of undefined
    at Server.verify (D:\S G ZALA\Test Code\node-poker-stack\game-server\node_modules\engine.io\lib\server.js:132:25)
    at Server.handleRequest (D:\S G ZALA\Test Code\node-poker-stack\game-server\node_modules\engine.io\lib\server.js:205:8)
    at Server.<anonymous> (D:\S G ZALA\Test Code\node-poker-stack\game-server\node_modules\engine.io\lib\server.js:432:12)
    at Server.<anonymous> (D:\S G ZALA\Test Code\node-poker-stack\game-server\node_modules\pomelo\node_modules\socket.io\lib\index.js:275:16)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:691:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)`

**Comment by Mtigrini** [comment]
Hey! Issue can be resolved by setting the transport in server.js, like this : 
var app = pomelo.createApp();
app.set('name', 'poker-game-stack');

app.configure('production|development', function(){
  app.set('connectorConfig', {
    connector: pomelo.connectors.sioconnector,
    // 'websocket', 'polling-xhr', 'polling-jsonp', 'polling'
    transports: ['websocket', 'polling'],
    heartbeats: true,
    closeTimeout: 60 * 1000,
    heartbeatTimeout: 60 * 1000,
    heartbeatInterval: 25 * 1000
  });
	app.route('game', routeUtil.game);
	app.filter(pomelo.timeout());
    app.set('session', require('../shared/config/session.json'));
});

Also, change pomelo version in package.json to 2.2.x as 1.0.0 is deprecated. Should do the trick.

**Comment by kyle-tinroof** [comment]
@Mtigrini I'm also running into the same issue.
After following your instructions, no errors on game-server side.
But on the web-server side I am getting this:
![image](https://user-images.githubusercontent.com/63257034/82937399-1bc72680-9f5e-11ea-8034-44c5bd2b015f.png)

**Comment by xprv17** [comment]
I had the same issue and I couldnt resolve it with a code bellow from @Mtigrini . Would appreciate any help.
