### ISSUE TITLE
'indexOf' of undefined

### ISSUE THREAD

**Issue by xprv17** [vampserv/node-poker-stack#13]
I setup everything and got this code console error:

[ERROR] console - Caught exception: TypeError: Cannot read property 'indexOf' of undefined
    at Server.verify (/home/ubuntu/node-poker-stack-master/node_modules/engine.io/lib/server.js:132:25)
    at Server.handleRequest (/home/ubuntu/node-poker-stack-master/node_modules/engine.io/lib/server.js:205:8)
    at Server.<anonymous> (/home/ubuntu/node-poker-stack-master/node_modules/engine.io/lib/server.js:432:12)
    at Server.<anonymous> (/home/ubuntu/node-poker-stack-master/node_modules/socket.io/lib/index.js:275:16)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:691:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)

Any help would be much appreciated

**Comment by anthnyprschka** [comment]
Same
