### ISSUE TITLE
module.js not found

### ISSUE THREAD

**Issue by avjiang** [vampserv/node-poker-stack#2]
Hi, i have some issue in installing the package. When i run command prompt in my windows with command node app.js after i cd to the directory, the module.js is not found. i am new to node.js . can you please explain to me what is wrong? thank you

**Comment by 0x7426078620226** [comment]
I also encountered the same error. 

![image](https://cloud.githubusercontent.com/assets/10267514/16556284/60bb0066-4203-11e6-8da4-476aa34c1b1c.png)

please support!
Thanks!

**Comment by 0x7426078620226** [comment]
I've run this by running the file 'npm-install.bat' before.

but meet new problems as it did not show anything, bug right line: xhr.send (null); socket.io.js

![image](https://cloud.githubusercontent.com/assets/10267514/16557259/f0a08098-4208-11e6-8e17-ce03cb27a097.png)

Thanks!

**Comment by MathGasciolli** [comment]
I have the same problem... Did run the script npm-install.sh before...
It says "can't find the module powelo".

And I have the same localhost page as talatabao :(

**Comment by blademaster-888** [comment]
I have the same problem:
It says "can't find the module powelo".

I think this build requires the old version of npm. im gona try node.js 4.4.1 since it is around 2015.. hope it works...

**Comment by MathGasciolli** [comment]
Okay thanks for the answer, tell me if you can make it work ! :)

Have a good day

________________________________

**Comment by blademaster-888** [comment]
it seems when i tried a very early version of node.js. installed without errors... i went back to node.js version 0.10.25 which comes with npm version 1.3.24.

however, when I tried to run gameserver/app i get errors:

![image](https://user-images.githubusercontent.com/1754262/29501518-45cf0ea6-866c-11e7-845c-5c02af4514b1.png)

**Comment by blademaster-888** [comment]
Then I try to tried to install again and when I tried running I get 👍 
![image](https://user-images.githubusercontent.com/1754262/29501630-6eaf89ee-866d-11e7-8b0e-55c987cc6797.png)

Can the dev please tell me which Node.js or NPM version works or point out whats the problem with this. I really want to get into knowing how this poker server works. thanks.

**Comment by blademaster-888** [comment]
Ok. I got it to work. For anyone that's interested. heres the instructions how to run it(at least how I did it):
Before you begin uninstall all previous node.js or npm on system and even clear caches or delete node directory just to be safe.

1. download latest node.js(for me its x64 windows so i downloaded 6.11.2) and install it on your system.
2. clone project by typing 
 git clone https://github.com/vampserv/node-poker-stack.git
3. cd node-poker-stack:
4. Install pomelo globally(on windows it installs to C:\Users\[yourusername]\AppData\Roaming\npm\node_modules):
   npm install -g pomelo
5. install game:
  sh npm-install.sh
6. run webserver:
  node web-server/app
7. open another bash and run game server:
  cd game-server
  pomelo start
8. open web browser and load page:
  localhost:3002

9 If everyone went well. try to register and user name and password and u will be able to login.

My result just to prove that it's working:


![image](https://user-images.githubusercontent.com/1754262/29595470-f15e70e2-87fa-11e7-9ae2-fec489bb402a.png)


Have fun learning!

**Comment by Victor1811** [comment]
@telostia 
I get error at 7. at :pomelo start : 


pomelo start                                                                   
internal/modules/cjs/loader.js:584                                                  
 throw err;                                                                  
     ^                                                                                                                                                             Error: Cannot find module 'C:\Users\Victor\Desktop\pomelo\bin\pomelo'   
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)      
at Function.Module._load (internal/modules/cjs/loader.js:508:25)                 
at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)              
 at startup (internal/bootstrap/node.js:283:19)                                  
 at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
--


anybody has any idea?
followed all your steps!
